dist: xenial
language: generic
sudo: false
cache:
  directories:
  - $HOME/.stack/

# We allow stack to be mutable, floating to the latest stable (sigh, non-hermetic):
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- cat /proc/cpuinfo | grep name

install:
  - stack --no-terminal --install-ghc test --only-dependencies 

script:
  - stack test --no-terminal --haddock --no-haddock-deps
